### ISSUE TITLE
Request: add BTC based markets

### ISSUE THREAD

**Issue by volandku** [OttoAllmendinger/gnome-shell-bitcoin-markets#54] opened 2017-12-12 02:27 UTC
I didnt found any pairs like BTC\LTC BTC\ETH BTC\XMR and so on.
Could you add it in next releases?

**Comment by OttoAllmendinger** [comment] 2017-12-12 18:01
Good idea :)

**Comment by OttoAllmendinger** [comment] 2018-11-22 09:54
duplicate of #74

**Closed by OttoAllmendinger** 2018-11-22 09:54 UTC
