### ISSUE TITLE
GNOME 41

### ISSUE THREAD

**Issue by iatmik** [OttoAllmendinger/gnome-shell-bitcoin-markets#123] opened 2021-11-13 09:40 UTC
can anyone explain how I alter the metadata so this works in 41 ?

**Comment by iatmik** [comment] 2021-11-14 07:28
{
  "shell-version": ["3.32", "3.34", "3.36", "3.38","3.41"],
  "uuid": "bitcoin-markets@ottoallmendinger.github.com",
  "name": "Bitcoin Markets",
  "url": "https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/",
  "description": "Display info on various crypto-currency exchanges.",
  "settings-schema": "org.gnome.shell.extensions.bitcoin-markets",
  "gettext-domain": "gnome-shell-bitcoin-markets",
  "git-version": "_gitversion_"
,

is this correct?

**Comment by OttoAllmendinger** [comment] 2021-11-20 14:45
duplicate of #120

**Closed by OttoAllmendinger** 2021-11-20 14:45 UTC
