### ISSUE TITLE
Support for Kinetic/Gnome Shell 43

### ISSUE THREAD

**Issue by MatzFan** [OttoAllmendinger/gnome-shell-bitcoin-markets#138] opened 2022-10-22 21:39 UTC
Just upgraded to Kinetic Kudu and noticed that the extension is incompatible with gnome-shell 43.

**Comment by OttoAllmendinger** [comment] 2022-10-25 13:54
duplicate of #136

**Closed by OttoAllmendinger** 2022-10-25 13:54 UTC
