### ISSUE TITLE
Soup.SessionAsync is not a constructor

### ISSUE THREAD

**Issue by str** [OttoAllmendinger/gnome-shell-bitcoin-markets#139] opened 2022-10-28 15:49 UTC
After updating to Ubuntu 22.10 the addon is not working anymore. It shows this error message when I hover it

![image](https://user-images.githubusercontent.com/123817/198679398-fa57a154-922f-416c-9823-52e157f4be11.png)

**Comment by OttoAllmendinger** [comment] 2022-11-07 07:30
duplicate of #136

**Closed by OttoAllmendinger** 2022-11-07 07:30 UTC
